modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="summon_mutant_magic_addon"
version="1.0.0"
displayName="Summon Mutant Magic Addon"
description="Addon que invoca mutantes com magia"
