
modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="summonmutantmagic"
version="1.0"
displayName="Summon Mutant Magic Addon"
description="Addon que adiciona summons mutantes e magias ao Iron's Spellbooks."

[[dependencies.summonmutantmagic]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
