name: Build Darkness Mod

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-cache-${{ runner.os }}-

      - name: Run Gradle build (uses Gradle Action to install Gradle if wrapper missing)
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build

      - name: Find produced jars (debug)
        run: |
          echo "List build directory:"
          ls -la build || true
          ls -la build/libs || true
          find . -type f -name "*.jar" -maxdepth 6 || true

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mod-jars
          path: |
            build/libs/**/*.jar
            build/**/libs/**/*.jar
            **/build/libs/**/*.jar
            **/*.jar
