name: Build Darkness Mod

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
    - uses: actions/upload-artifact@v4

        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --stacktrace --info

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: Summon-Mutant-Magic-Addon
          path: build/libs/*.jar
