name: Build Darkness Mod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Dar permissão ao gradlew
        run: chmod +x gradlew

      - name: Build com Gradle
        run: ./gradlew build

      - name: Upload JAR gerado
        uses: actions/upload-artifact@v4
        with:
          name: Darkness-Mod
          path: build/libs/*.jar
